name: Grill Mór
favicon: null
layout_spectrum: 0.5020104362629354
typography_spectrum: 0.19218630250543356
title: grill-mor
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d63b03'
    - '#4c050d'
    - '#fe7e01'
    - '#ffba03'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
